[package]
name = "crypto-bigint"
version = "0.5.5"
description = """
Pure Rust implementation of a big integer library which has been designed from
the ground-up for use in cryptographic applications. Provides constant-time,
no_std-friendly implementations of modern formulas using const generics.
"""
resolver = "2"
edition = "2021"

[dependencies]
subtle = { version = "2.4", default-features = false }
zeroize = { version = "1", optional = true, default-features = false }

[features]
default = ["zeroize"]
